
spring:
  application:
    name: product1
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://39.108.156.206:3306/SpringCloud_Sell?characterEncoding=utf-8
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/